import React, { useEffect, useRef, useState } from 'react';

// Using arbitrary types for JSXGraph since it doesn't have official TS definitions installed
declare const JXG: any;

const ENABLE_UNSAFE_JSXGRAPH_SCRIPT = import.meta.env.VITE_ENABLE_UNSAFE_JSXGRAPH_SCRIPT === 'true';
const JSXGRAPH_CDN_URL = 'https://cdn.jsdelivr.net/npm/jsxgraph/distrib/jsxgraphcore.js';
const BLOCKED_JSXGRAPH_TOKENS = [
  'window',
  'document',
  'eval',
  'Function',
  'fetch',
  'XMLHttpRequest',
  'localStorage',
  'sessionStorage',
  'postMessage',
  'WebSocket',
  'import('
];

function isSafeScriptCode(script: string): boolean {
  const normalized = script.replace(/\s+/g, ' ').trim();
  return !BLOCKED_JSXGRAPH_TOKENS.some((token) => normalized.includes(token));
}

let jsxgraphLoaderPromise: Promise<any> | null = null;

function loadJXGFromTrustedSource(): Promise<any> {
  if ((window as any).JXG) {
    return Promise.resolve((window as any).JXG);
  }

  if (!ENABLE_UNSAFE_JSXGRAPH_SCRIPT) {
    return Promise.resolve(null);
  }

  if (jsxgraphLoaderPromise) {
    return jsxgraphLoaderPromise;
  }

  jsxgraphLoaderPromise = new Promise((resolve, reject) => {
    const existing = document.querySelector(`script[data-jxg-src="${JSXGRAPH_CDN_URL}"]`) as HTMLScriptElement | null;
    if (existing) {
      existing.addEventListener('load', () => resolve((window as any).JXG));
      existing.addEventListener('error', () => reject(new Error('Failed to load JSXGraph script')));
      return;
    }

    const script = document.createElement('script');
    script.src = JSXGRAPH_CDN_URL;
    script.async = true;
    script.defer = true;
    script.setAttribute('data-jxg-src', JSXGRAPH_CDN_URL);
    script.onload = () => resolve((window as any).JXG);
    script.onerror = () => reject(new Error('Failed to load JSXGraph script'));
    document.head.appendChild(script);
  });

  return jsxgraphLoaderPromise;
}

interface GeometryWorkspaceProps {
  boardId?: string;
  elements?: any[]; // We can pass definitions to render (points, lines, circles)
  scriptCode?: string; // JavaScript code string to execute for JXG
}

export const GeometryWorkspace: React.FC<GeometryWorkspaceProps> = ({ 
  boardId, 
  elements = [], 
  scriptCode
}) => {
  const boardRef = useRef<any>(null);
  const [targetId] = useState<string>(() => boardId || `jxgbox-${Math.random().toString(36).substr(2, 9)}`);

  useEffect(() => {
    loadJXGFromTrustedSource().then((JXG) => {

      if (!JXG) {
          console.warn('JSXGraph runtime not available. Enable VITE_ENABLE_UNSAFE_JSXGRAPH_SCRIPT=true in trusted environments to render jsxgraph blocks.');
          return;
      }

      if (boardRef.current) {
        JXG.JSXGraph.freeBoard(boardRef.current);
      }

      try {
        const board = JXG.JSXGraph.initBoard(targetId, {
          boundingbox: [-10, 10, 10, -10],
          axis: true,
          showCopyright: false,
          grid: true,
          keepaspectratio: true,
        });

        boardRef.current = board;

        // If there is customized script code generated by NanoBanana logic
        if (scriptCode) {
          if (!ENABLE_UNSAFE_JSXGRAPH_SCRIPT) {
            console.warn('JSXGraph script execution is disabled by default. Set VITE_ENABLE_UNSAFE_JSXGRAPH_SCRIPT=true only in trusted environments.');
          } else if (!isSafeScriptCode(scriptCode)) {
            console.warn('Blocked potentially unsafe JSXGraph script content.');
          } else {
            const executeScript = new Function('board', 'JXG', scriptCode);
            executeScript(board, JXG);
          }
        } else if (elements.length > 0) {
          // Render generic elements
          elements.forEach(el => {
            if (el.type === 'point') {
               board.create('point', el.coords, { name: el.name || '', size: 3, colors: el.color || 'blue' });
            } else if (el.type === 'line') {
               // coords should be [point1Name, point2Name] or coordinates
               const p1 = board.create('point', el.p1, {visible: false});
               const p2 = board.create('point', el.p2, {visible: false});
               board.create('line', [p1, p2], { strokeColor: el.color || 'red', straightFirst: false, straightLast: false });
            }
          });
        }
      } catch (err) {
        console.error("Failed to render JSXGraph board", err);
      }
    });

    return () => {
      if (boardRef.current && (window as any).JXG) {
        (window as any).JXG.JSXGraph.freeBoard(boardRef.current);
      }
    };
  }, [scriptCode, elements, targetId]);

  return (
    <div 
      id={targetId} 
      className="jxgbox w-full h-[500px] mx-auto rounded-xl border border-slate-300 shadow-sm bg-white"
    />
  );
};
