import React, { useEffect, useRef } from 'react';

// Using arbitrary types for JSXGraph since it doesn't have official TS definitions installed
declare const JXG: any;

interface GeometryWorkspaceProps {
  boardId?: string;
  elements?: any[]; // We can pass definitions to render (points, lines, circles)
  width?: number | string;
  height?: number | string;
  scriptCode?: string; // JavaScript code string to execute for JXG
}

export const GeometryWorkspace: React.FC<GeometryWorkspaceProps> = ({ 
  boardId = 'jxgbox', 
  elements = [], 
  width = '100%', 
  height = '500px',
  scriptCode
}) => {
  const boardRef = useRef<any>(null);

  useEffect(() => {
    // Dynamic import to avoid SSR issues if ever ported to Next.js
    import('jsxgraph').then((JXGModule) => {
      // JSXGraph binds to window/global usually. 
      // JXG.JSXGraph.initBoard
      const JXG = window.JXG || JXGModule.default || JXGModule;

      if (!JXG) {
          console.error("JSXGraph not loaded properly");
          return;
      }

      if (boardRef.current) {
        JXG.JSXGraph.freeBoard(boardRef.current);
      }

      try {
        const board = JXG.JSXGraph.initBoard(boardId, {
          boundingbox: [-10, 10, 10, -10],
          axis: true,
          showCopyright: false,
          grid: true,
          keepaspectratio: true,
        });

        boardRef.current = board;

        // If there is customized script code generated by NanoBanana logic
        if (scriptCode) {
           const executeScript = new Function('board', 'JXG', scriptCode);
           executeScript(board, JXG);
        } else if (elements.length > 0) {
          // Render generic elements
          elements.forEach(el => {
            if (el.type === 'point') {
               board.create('point', el.coords, { name: el.name || '', size: 3, colors: el.color || 'blue' });
            } else if (el.type === 'line') {
               // coords should be [point1Name, point2Name] or coordinates
               const p1 = board.create('point', el.p1, {visible: false});
               const p2 = board.create('point', el.p2, {visible: false});
               board.create('line', [p1, p2], { strokeColor: el.color || 'red', straightFirst: false, straightLast: false });
            }
          });
        }
      } catch (err) {
        console.error("Failed to render JSXGraph board", err);
      }
    });

    return () => {
      if (boardRef.current && window.JXG) {
        window.JXG.JSXGraph.freeBoard(boardRef.current);
      }
    };
  }, [scriptCode, elements, boardId]);

  return (
    <div 
      id={boardId} 
      className="jxgbox rounded-xl border border-slate-300 shadow-sm bg-white" 
      style={{ width, height, margin: '0 auto' }} 
    />
  );
};
